CREATE TABLE IF NOT EXISTS users (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    surname VARCHAR(255) NOT NULL,
    person_id VARCHAR(12) NOT NULL UNIQUE,
    uuid VARCHAR(36) NOT NULL UNIQUE
);
